services:
  zinc:
    image: public.ecr.aws/zinclabs/zincsearch:latest
    environment:
      - ZINC_FIRST_ADMIN_USER=${ZINC_FIRST_ADMIN_USER}
      - ZINC_FIRST_ADMIN_PASSWORD=${ZINC_FIRST_ADMIN_PASSWORD}
      - MAX_RESULTS=1000000
      - ZINC_MAX_RESULTS=1000000
    ports:
      - '4080:4080'
    volumes:
      - zinc_data:/var/lib/zinc
    networks:
      - email_indexer_net
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    depends_on:
      - zinc
    environment:
      - APP_NAME=email backend api
      - VERSION=0.0.1
      - ZINC_SEARCH_API_URL=http://zinc:4080
      - ZINC_SEARCH_AUTH_USER=${ZINC_FIRST_ADMIN_USER}
      - ZINC_SEARCH_AUTH_PASS=${ZINC_FIRST_ADMIN_PASSWORD}
      - HTTP_PORT=${HTTP_PORT}
      - ACCEPTED_DOMAINS=http://localhost:8080
      - APP_ENV=development
    ports:
      - '8000:${HTTP_PORT}'
    restart: on-failure
    volumes:
      - ./backend:/app
    networks:
      - email_indexer_net

  frontend:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    environment:
      - VITE_BASE_URL=http://backend:8000
    ports:
      - 8080:80
    restart: on-failure
    volumes:
      - ./frontend:/app
    networks:
      - email_indexer_net

networks:
  email_indexer_net:
    driver: bridge

volumes:
  zinc_data: