version: '3'
services:
  zinc:
    image: public.ecr.aws/zinclabs/zincsearch:latest
    environment:
      - ZINC_FIRST_ADMIN_USER=${ZINC_FIRST_ADMIN_USER}
      - ZINC_FIRST_ADMIN_PASSWORD=${ZINC_FIRST_ADMIN_PASSWORD}
    ports:
      - '4080:4080'
    volumes:
      - zinc_data:/var/lib/zinc
    networks:
      - email_indexer_net

networks:
  email_indexer_net:
    driver: bridge

volumes:
  zinc_data: